#!/usr/bin/env sh

file="/tmp/touchpad_disabled"
command="hyprctl keyword device[asue120a:00-04f3:319b-touchpad]:enabled"

if [ -f "$file" ]; then
  $command true
  rm "$file"
else
  $command false
  touch "$file"
fi

