
[profile.dev]
opt-level=1

[profile.dev.package."*"]
opt-level = 3 # I don't really care about dependency build time
strip = "debuginfo"

[profile.release]
strip = true
lto = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zlinker-features=-lld"] # fix nightly bug

