
[config]
# broken
# reload_apps = true

[config.reload_apps_list]
gtk_theme = true
kitty = true
dunst = true

# disabled because of how ugly the theme is
# [templates.gtk]
# input_path = "~/dotfiles/external/templates/gtk.css"
# output_path = "~/.config/gtk-4.0/gtk.css"

[templates.firefox]
input_path = "~/dotfiles/external/templates/colors.json"
output_path = "~/.cache/wal/colors.json"

